const MEDIUM_SCREEN_BREAKPOINT = 1024;
const SMALL_SCREEN_BREAKPOINT = 935;
const XSMALL_SCREEN_BREAKPOINT = 560;

export {MEDIUM_SCREEN_BREAKPOINT, SMALL_SCREEN_BREAKPOINT, XSMALL_SCREEN_BREAKPOINT};
